### ISSUE TITLE
SeleniumIDEDoc/Install.md--第一幅图下面的文字错误

### ISSUE THREAD

**Issue by majianwei04** [wangding/selenium-ide-doc#1]
![image](https://cloud.githubusercontent.com/assets/23111496/20251580/42ecc3fc-aa55-11e6-9ff9-914d49a9c00e.png)
应为火狐浏览器。

**Comment by wangding** [comment]
你直接 Fork 之后，修改完了，pull request 吧。

**Comment by wangding** [comment]
在刘金梦的 #5 pull request 中已经修改了。 😄

**Comment by wangding** [comment]
在刘金梦的 #5 pull request 中已经修改了。 😄
