### ISSUE TITLE
[bug]语句不通顺

### ISSUE THREAD

**Issue by liweiweiLWW** [wangding/selenium-ide-doc#2]
制作测试案例——>录制  最后
![image](https://cloud.githubusercontent.com/assets/23024716/20256041/04be504c-aa7c-11e6-9c83-6a5923f87e75.png)

建议修改：
type命令：点击网页的某些区域时才能录制

**Comment by wangding** [comment]
应该去掉一个多余的“的”字。可以改成：type命令需要点击网页的某些区域才能录制。还是 pull request 吧。
