### ISSUE TITLE
【bug】语句不通顺

### ISSUE THREAD

**Issue by gaoyang836** [wangding/selenium-ide-doc#4]
**SeleniumIDEDoc/Selenese.md**

Action 动作类命令中，下面一句不通顺：

他们做的事情，类似：点击这个链接、选择那个选项。如果动作失败，或者有错误，当前测试会停止执行。

建议修改：
这类命令的作用是：点击某个链接、选择某个选项后，如果动作失败或有错误，当前测试就会停止执行。

**Comment by wangding** [comment]
你理解的不对啊，你看一下源英文文档啊。

**Comment by gaoyang836** [comment]
对不起，没仔细看英语文档，只是想语言修改更通顺，却已经偏离原意
