### ISSUE TITLE
【bug】语法错误

### ISSUE THREAD

**Issue by gaomengyao** [wangding/selenium-ide-doc#6]
IDE的功能--测试用例面板：默认情况下，是 HTML，当然可以改变成其他编程语言，如 Java 或 C#，或像 Python 这样的脚本语言（缺少主语）
应修改为： 默认情况下，测试用例文件的原生格式是 HTML，当然可以改变成其他编程语言，如 Java 或 C#，或像 Python 这样的脚本语言

**Comment by wangding** [comment]
你可以 fork 之后，修改完了，pull request。
